[package]
name = "AOSKitDemo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objc = "0.2.7"

[build-dependencies]
cc = "1.0.78"
gcc = "0.3.55"
